name: Build Android APK
run-name: Build - ${{ github.event.inputs.repository }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com"
      branchName:
        description: "Branch [Optional]"
        required: false
        default: "master"
      subdir:
        description: "Subdirectory (Use 'DodoBank')"
        required: false
        default: "DodoBank"
      taskName:
        description: "Task: assembleDebug"
        required: false
        default: "assembleDebug"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Clone project
        run: |
          git clone --recurse-submodules --depth=1 --branch ${{ github.event.inputs.branchName }} ${{ github.event.inputs.repository }} workspace

      - name: Build APK
        working-directory: ./workspace/${{ github.event.inputs.subdir }}
        run: |
          # Forzar Gradle antiguo para compatibilidad con 2017
          gradle wrapper --gradle-version 4.10.3
          chmod +x gradlew
          
          # Ejecutar la compilación
          ./gradlew ${{ github.event.inputs.taskName }} --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: workspace/**/*.apk
          name: apk-archive
          retention-days: 1
